apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: default          # <--- add this line
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: akyldocker25/nginx-argo:d44da0d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: default          # <--- add this line
spec:
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
